
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat-app
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      # - /app/node_modules       # hindari konflik host <-> container
    command: ["nodemon", "src/server.js"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:
      - ./client:/app
      # - /app/node_modules       # juga hindari konflik untuk React
    stdin_open: true            # untuk hot reload React
    tty: true
    command: ["npm", "run", "start:poll"]

volumes:
  mongo-data:
